// <auto-generated />
using Backend.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251126115839_SeedPlayers")]
    partial class SeedPlayers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageDetail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<decimal?>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ShirtName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Team")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Image = "https://assets.laliga.com/squad/2025/t178/p593109/128x128/p593109_t178_2025_1_002_000.jpg",
                            Name = "Lamine Yamal",
                            Points = 0,
                            Position = 3,
                            Price = 10m,
                            Team = "Barcelona"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Luka Modric",
                            Points = 0,
                            Position = 2,
                            Price = 12m,
                            Team = "Real Madrid"
                        },
                        new
                        {
                            Id = 3,
                            Image = "https://assets.laliga.com/squad/2025/t178/p77318/128x128/p77318_t178_2025_1_002_000.jpg",
                            ImageDetail = "https://r2.thesportsdb.com/images/media/player/render/agtip81658424227.png/small",
                            Name = "Marc-André ter Stegen",
                            Points = 0,
                            Position = 0,
                            Price = 9m,
                            Team = "Barcelona"
                        },
                        new
                        {
                            Id = 4,
                            Image = "https://assets.laliga.com/squad/2025/t186/p244855/128x128/p244855_t186_2025_1_002_000.jpg",
                            Name = "Jude Bellingham",
                            Points = 0,
                            Position = 2,
                            Price = 13m,
                            Team = "Real Madrid"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Antoine Griezmann",
                            Points = 0,
                            Position = 3,
                            Price = 11m,
                            Team = "Atlético de Madrid"
                        },
                        new
                        {
                            Id = 6,
                            Image = "https://assets.laliga.com/squad/2025/t175/p81352/128x128/p81352_t175_2025_1_002_000.jpg",
                            Name = "Jan Oblak",
                            Points = 0,
                            Position = 0,
                            Price = 9m,
                            Team = "Atlético de Madrid"
                        },
                        new
                        {
                            Id = 7,
                            Image = "https://assets.laliga.com/squad/2025/t185/p80209/128x128/p80209_t185_2025_1_002_000.jpg",
                            Name = "Isco",
                            Points = 0,
                            Position = 2,
                            Price = 8m,
                            Team = "Real Betis"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Borja Iglesias",
                            Points = 0,
                            Position = 3,
                            Price = 8m,
                            Team = "Real Betis"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Unai Simón",
                            Points = 0,
                            Position = 0,
                            Price = 8m,
                            Team = "Athletic Club"
                        },
                        new
                        {
                            Id = 10,
                            Image = "https://assets.laliga.com/squad/2025/t174/p197334/128x128/p197334_t174_2025_1_002_000.jpg",
                            Name = "Iñaki Williams",
                            Points = 0,
                            Position = 3,
                            Price = 9m,
                            Team = "Athletic Club"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Takefusa Kubo",
                            Points = 0,
                            Position = 3,
                            Price = 8m,
                            Team = "Real Sociedad"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Mikel Merino",
                            Points = 0,
                            Position = 2,
                            Price = 8m,
                            Team = "Real Sociedad"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Álex Remiro",
                            Points = 0,
                            Position = 0,
                            Price = 7m,
                            Team = "Real Sociedad"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Gerard Moreno",
                            Points = 0,
                            Position = 3,
                            Price = 9m,
                            Team = "Villarreal"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Dani Parejo",
                            Points = 0,
                            Position = 2,
                            Price = 8m,
                            Team = "Villarreal"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Álvaro Valles",
                            Points = 0,
                            Position = 0,
                            Price = 7m,
                            Team = "Las Palmas"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Jonathan Viera",
                            Points = 0,
                            Position = 2,
                            Price = 7m,
                            Team = "Las Palmas"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Enes Ünal",
                            Points = 0,
                            Position = 3,
                            Price = 7m,
                            Team = "Getafe"
                        },
                        new
                        {
                            Id = 19,
                            Name = "David Soria",
                            Points = 0,
                            Position = 0,
                            Price = 7m,
                            Team = "Getafe"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Joselu",
                            Points = 0,
                            Position = 3,
                            Price = 8m,
                            Team = "Real Madrid"
                        },
                        new
                        {
                            Id = 21,
                            Image = "https://assets.laliga.com/squad/2025/t178/p490541/128x128/p490541_t178_2025_1_002_000.jpg",
                            Name = "Pedri",
                            Points = 0,
                            Position = 2,
                            Price = 10m,
                            Team = "Barcelona"
                        },
                        new
                        {
                            Id = 22,
                            Image = "https://assets.laliga.com/squad/2025/t178/p56764/128x128/p56764_t178_2025_1_002_000.jpg",
                            Name = "Robert Lewandowski",
                            Points = 0,
                            Position = 3,
                            Price = 12m,
                            Team = "Barcelona"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Koke",
                            Points = 0,
                            Position = 2,
                            Price = 8m,
                            Team = "Atlético de Madrid"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Ángel Correa",
                            Points = 0,
                            Position = 3,
                            Price = 8m,
                            Team = "Atlético de Madrid"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Claudio Bravo",
                            Points = 0,
                            Position = 0,
                            Price = 7m,
                            Team = "Real Betis"
                        },
                        new
                        {
                            Id = 26,
                            Image = "https://assets.laliga.com/squad/2025/t185/p441303/128x128/p441303_t185_2025_1_002_000.jpg",
                            Name = "Aitor Ruibal",
                            Points = 0,
                            Position = 1,
                            Price = 7m,
                            Team = "Real Betis"
                        },
                        new
                        {
                            Id = 27,
                            Image = "https://assets.laliga.com/squad/2025/t174/p197319/128x128/p197319_t174_2025_1_002_000.jpg",
                            Name = "Yeray Álvarez",
                            Points = 0,
                            Position = 1,
                            Price = 7m,
                            Team = "Athletic Club"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Mikel Oyarzabal",
                            Points = 0,
                            Position = 3,
                            Price = 8m,
                            Team = "Real Sociedad"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Pau Torres",
                            Points = 0,
                            Position = 1,
                            Price = 7m,
                            Team = "Villarreal"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Sergio Herrera",
                            Points = 0,
                            Position = 0,
                            Price = 7m,
                            Team = "Osasuna"
                        },
                        new
                        {
                            Id = 31,
                            Image = "https://assets.laliga.com/squad/2025/t191/p132105/128x128/p132105_t191_2025_1_002_000.jpg",
                            Name = "José Gayà",
                            Points = 0,
                            Position = 1,
                            Price = 7m,
                            Team = "Valencia"
                        },
                        new
                        {
                            Id = 32,
                            Image = "https://assets.laliga.com/squad/2025/t2893/p517333/128x128/p517333_t2893_2025_1_002_000.jpg",
                            Name = "Arnau Martínez",
                            Points = 0,
                            Position = 1,
                            Price = 7m,
                            Team = "Girona"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
